language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_install:
  - mkdir -p build/logs
  - mkdir -p ~/.composer
  - composer require satooshi/php-coveralls:dev-master
  - composer install --dev --no-interaction
  - travis_retry composer self-update

install:
  - travis_retry composer install

before_script:
- composer self-update -q
- if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
script:
- phpunit

after_script:
  - php vendor/satooshi/php-coveralls/bin/coveralls -v
